name: svg-tree-antiquote

license: GPL

default-extensions:
  - QuasiQuotes
  - TemplateHaskell
  - LambdaCase

dependencies:
  - base
  - BNFC-meta
  - svg-tree
  - template-haskell
  - linear

library:
  source-dirs:
    - lib
